#Importing Library: Numpy
(From Last week's Lab, you can find more information about **"NumPy"** library).

NumPy is the fundamental Python library for numerical computing. 

In [ ]:
import numpy as np

#Importing Library: SciPy
(From Last week's Lab, you can find more information about **"SciPy"** library).

**SciPy** stands for Scientific python. For some statistical calculation we do need Scipy e.g, during last week, you have used stats from Scipy to calculate "Mode".



In [ ]:
from scipy import stats

#Importing Library: Math

**Math** is a library you can apply for performing mathematical tasks by using different Math methods in this library.

In [ ]:
import math as mt

#Importing Library: Random
Python has a built-in library **random** which can be used for generating random numbers/values


In [ ]:
import random as rnd 

#Matrix Operations:
There are different ways that we can represent Matrix in Python. We will see how we can represent Matrix using NumPy Library.

An example code is provided below:

In [ ]:
x = np.array( ((2,3), (3, 5)) ) 
y = np.array( ((1,2), (5, -1)) )
addition= x+y
print ("addition of x and y", addition )

subtraction = x-y 
print ("difference between x and y", subtraction )

dot_product= np.dot(x,y)
print ("dot product of x and y", dot_product )

print(x)
print(y)

addition of x and y [[3 5]
 [8 4]]
difference between x and y [[ 1  1]
 [-2  6]]
dot product of x and y [[17  1]
 [28  1]]
[[2 3]
 [3 5]]
[[ 1  2]
 [ 5 -1]]


There is another function in **NumPy** called **matrix()** that provide convinient notations of Matrix multiplication. Using the **matrix()** function when we will do x*y it actually gives us the "dot product multiplication" whereas, for NumPy array only does "element-wise" multiplication. 

Therefore, to find the multiplication in our previous example we used np.dot function for getting the multiplication while using numpy array. 

**Another important note,** Numpy matrix() is strictly two dimensional, while NumPy array can be of any dimension.

We have an example below, where we used NumPy Matrix to perform a matrix multiplication

In [ ]:
x = np.matrix( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )
multiplication = x * y
print ("multiplication of x and y", multiplication )


multiplication of x and y [[17  1]
 [28  1]]


#Question:1
You are given with metrices "a" contains ((35,45), (21,51)) , "b" contains ((1,2), (3,4)) and, "c" contains ((100,101), (200,201)). Now perform the following operations given:

***Hint:*** You can either use "array" or "matrix" function.

 

1.   a+b
2.   b-c
3. a*c
4.b.c

In [ ]:
a = np.array( ((35,45), (21, 51)) )
b = np.array( ((1,2), (3, 4)) )
c = np.array( ((100,101), (200, 201)) )

print(a+b)
print(b-c)
print(a*c)
print(np.dot(b,c))
print(np.dot(b,c))
print(np.dot(a,c))

[[36 47]
 [24 55]]
[[ -99  -99]
 [-197 -197]]
[[ 3500  4545]
 [ 4200 10251]]
[[ 500  503]
 [1100 1107]]
[[ 500  503]
 [1100 1107]]
[[12500 12580]
 [12300 12372]]


In [ ]:
a = np.array( ((35,45), (21, 51)) )
b = np.array( ((1,2), (3, 4)) )
c = np.array( ((100,101), (200, 201)) )
addition= a+b
print ("addition of a and b", addition )
subtraction = b-c
print ("difference between a and b", subtraction )
dot_product= np.dot(b,c)
print ("dot product of b and c", dot_product )
#a = np.matrix( ((45,35), (21, 51)) )
#c = np.matrix( ((100,101), (200, 201)) )
multiplication = a * c
print ("multiplication of a and c", multiplication )
#Alternatively,
dot_product= np.dot(a,c)
print ("dot product of a and c", dot_product )


addition of a and b [[36 47]
 [24 55]]
difference between a and b [[ -99  -99]
 [-197 -197]]
dot product of b and c [[ 500  503]
 [1100 1107]]
multiplication of a and c [[ 3500  4545]
 [ 4200 10251]]
dot product of a and c [[12500 12580]
 [12300 12372]]


In [ ]:
#Solution:
a = np.array( ((45,35), (21, 51)) )
b = np.array( ((1,2), (3, 4)) )
c = np.array( ((100,101), (200, 201)) )
addition= a+b
print ("addition of a and b", addition )
subtraction = b-c
print ("difference between a and b", subtraction )
dot_product= np.dot(b,c)
print ("dot product of b and c", dot_product )
a = np.matrix( ((45,35), (21, 51)) )
c = np.matrix( ((100,101), (200, 201)) )
multiplication = a * c
print ("multiplication of a and c", multiplication )
#Alternatively,
dot_product= np.dot(a,c)
print ("dot product of a and c", dot_product )

addition of a and b [[46 37]
 [24 55]]
difference between a and b [[ -99  -99]
 [-197 -197]]
dot product of b and c [[ 500  503]
 [1100 1107]]
multiplication of a and c [[11500 11580]
 [12300 12372]]
dot product of a and c [[11500 11580]
 [12300 12372]]


#Vector Operations:
There are different ways that we can represent Vector in Python as well. We will see how we can represent Vector using NumPy Library.

An example code is provided below:

In [ ]:
x = np.array( [1, 2, 5] ) 
y = np.array( [5,-1, 6])
addition= x+y
print ("addition of x and y", addition )

subtraction = x-y 
print ("difference between x and y", subtraction )

multiplication = x*y
print ("multiplication between x and y", multiplication)

dot_product= np.dot(x,y)
print ("dot product of x and y", dot_product)



addition of x and y [ 6  1 11]
difference between x and y [-4  3 -1]
multiplication between x and y [ 5 -2 30]
dot product of x and y 33


There is no such function available for calculating Vector Modulus in NumPy or, in any other commony used Python libraries.

Therefore, there are several work arounds and here one of them is given below:

In [ ]:
x=np.array([1,2,3,4,5])

modulus=np.sqrt(np.dot(x,x)) #np.dot(v,v) multiplies the elements of v with themselves and squares them before adding
print(modulus)


7.416198487095663


We will now see an example of multiplication of vector with a scalar value. We can simply use multiply() function in this occassion.

In [ ]:
import numpy as np
vector = np.array([1, 2, 3])
n = 100
print(np.multiply(vector,n))
print(vector * n)
print(n * vector)
print(np.multiply(n,vector))

[100 200 300]
[100 200 300]
[100 200 300]
[100 200 300]


#Question:2
You are given with a vector/1D matrix, ([90,200,20,1,54,200]) contains the club card points he earned on different occassions. You are giving him 2 times more points and you want to store that 2 times rewarded points in a new vector/1D array. Write a code to store this infomation. 


In [ ]:
first = np.array([90,200,20,1,54,200])
second = np.multiply(2,first)
print(second)

[180 400  40   2 108 400]


In [ ]:
#SOLUTION
import numpy as np
vector = np.array([90,200,20,1,54,200])
n = 2
reward=np.multiply(vector,n)
print(reward)


[180 400  40   2 108 400]


#Generating Binomial Distribution:
We will now see how we can generate a Binomial Distribution and we will find the PMF, CMF and other statistical measures using **Stats** function from **SciPy** library.

Following is an example code given, for function binom(n=10,p=0.2), where, n is the number of trials and p holds the probability of success. 

In [ ]:
from scipy import stats
X = stats.binom(10, 0.2) # Declare X to be a binomial random variable
print(X.pmf(3))           # P(X = 3) which implies we are calculating the mass function for the third trial
print(X.cdf(4))           # P(X <= 4) which implies we are calculating cumulative distribution upto fourth trial
print(X.mean())           # Mean
print(X.var())            # Variance
print(X.std())            # Standard Deviation
print(X)

0.20132659200000022
0.9672065024000001
2.0
1.6
1.2649110640673518


#Question:3
You are given a dice which you can roll five times to check how many times you find "6" and probability of the roll being a success is 80%.  Write a code to find the probability mass function cumulative distribution function for the final trial.

In [ ]:
from scipy import stats
x = stats.binom(5, 0.8)
print(x.pmf(5))
x.cdf(5)

0.3276800000000001


1.0

In [ ]:
#Solution:
from scipy import stats
X = stats.binom(5, 0.8)
print(X.pmf(5))
print(X.cdf(5))

0.3276800000000001
1.0


#Generating Normal Distribution:
We will now see how we can generate a Normal Distribution and we will find the PDF, CDF and other statistical measures using Stats function from SciPy library. Here, we will also use Math library for some mathematical calculation.

Following is an example code given, for function norm(μ=3,σ2=16), where, μ is the mean and σ2 is the Variance. In theory we can use Variance for calculation, however, in **SciPy we need to use Standard Deviation**. Hence, we will calculate square root of Variance. 

In [ ]:
import math
from scipy import stats
A = stats.norm(3, math.sqrt(16)) # Declare A to be a normal random variable
print(A.pdf(4))       			 # f(4), the probability density at 4
print(A.cdf(2))                  # f(2)
print(A)

0.09666702920071232
0.4012936743170763


#Question:4
Write a code to calculate the probability density function and cumulative distrbution function for a normal distribution with μ=9 ,σ2=64, for probability density 6


In [ ]:
import math
from scipy import stats
A = stats.norm(9, math.sqrt(64)) 
print(A.pdf(6))       			 
print(A.cdf(6)) 

0.04648188673372112
0.3538302333272762


In [ ]:
#Solution:
import math
from scipy import stats
A = stats.norm(9, math.sqrt(64))
print(A.pdf(6))
print(A.cdf(6))


0.04648188673372112
0.3538302333272762


#Question:5
Write a code to calculate the probability density function for value "11" in the range, given, mean=10 and standard deviation=2.
**Hint:** remember to use standard deviation instead of variance in the code.

In [ ]:
import math
from scipy import stats
A = stats.norm(10,2) 
print(A.pdf(11)) 

0.17603266338214976


In [ ]:
#Solution:
from scipy import stats
A = stats.norm(10, 2)
print(A.pdf(11)) 

0.17603266338214976


#Calculating Probability and Conditional Probability:

Here, we will see examples of probability calculation from a random variable. To do so, we will use **random** library from python.

From a tossing coin we have two events in a sample space. The following code calculates the probability of getting head when we do hundred trials of flipp



In [ ]:
def toss_coin(n):
    trials = []
    for i in range(n):
        trials.append(rnd.random() <= 0.5) #we are considering 50% or below will be the probability of getting heads from random flips
    return sum(trials) #returns the event count for observed heads from coin flips

def probability(n, e):
  probability_heads=(e/n)
  return probability_heads


n=10

probability_heads =probability(n, toss_coin(n))
print(probability_heads)

n=100
probability_heads =probability(n, toss_coin(n))
print(probability_heads)

n=1000
probability_heads =probability(n, toss_coin(n))
print(probability_heads)

0.5
0.49
0.524


#Question: 6
Now, calculate the probability of finding  "Tails" when you toss a fair coin. 

In [ ]:
def toss_coin(n):
    trials = []
    for i in range(n):
        trials.append(rnd.random() <= 0.5) #we are considering 50% or below will be the probability of getting heads from random flips
    return sum(trials) #returns the event count for observed heads from coin flips

def probability(n, e):
  probability_tails=(e/n)
  return probability_tails


n=10

probability_tails =probability(n, toss_coin(n))
print(probability_tails)

n=100
probability_tails =probability(n, toss_coin(n))
print(probability_tails)

n=1000
probability_tails =probability(n, toss_coin(n))
print(probability_tails)

0.3
0.39
0.502


#Question:7 (More Challenging)
Write a code to find the probability of both Heads and Tails for the same number of trials.

In [ ]:
import numpy as np
def coinFlip(p):    
    #perform the binomial distribution (returns 0 or 1)    
    result = np.random.binomial(1,p)
#return flip to be added to numpy array    
    return result
'''Main Area'''
#probability of heads vs. tails. This can be changed.
probability = .5
#num of flips required. This can be changed.
n = 100
#initiate array
fullResults = np.arange(n)
#perform desired numbered of flips at required probability set above
for i in range(0, n):    
    fullResults[i] = coinFlip(probability)    
    i+=1
#print results
print("probability is set to ", probability)
print("Tails = 0, Heads = 1: ", fullResults)
#Total up heads and tails for easy user experience 
print("Head Count: ", np.count_nonzero(fullResults == 1))
print("Tail Count: ", np.count_nonzero(fullResults == 0))

probability is set to  0.5
Tails = 0, Heads = 1:  [0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 0 0 1
 1 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 1 0
 1 0 1 0 0 0 1 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1 1 1 0 0]
Head Count:  53
Tail Count:  47


In [ ]:
#Solution:
import random
def toss_coin(n):
    trial_heads = 0
    trial_tails = 0
    for i in range(n):
        if random.random() <= 0.5:
            trial_heads+=1 #counting the number of heads observed over n trials
        else:
            trial_tails+=1 #counting the number of tails observed over n trials
            heads_n_tails=[0,0]
            heads_n_tails[0]=trial_heads
            heads_n_tails[1]=trial_tails
    return heads_n_tails #returns the total of all trial head and tails counts
def probability(n, event):
 probability_heads=(event[0]/n) # event[0] contains total count of all head events
 probability_tails=(event[1]/n) # event[1] contains total count of all tail events
 p=[probability_heads,probability_tails]
 return p # returns probability of both head and tail events
n=10
probability_heads_n_tails=probability(n, toss_coin(n))
probability_heads=probability_heads_n_tails[0]
print(probability_heads)
probability_tails=probability_heads_n_tails[1]
print(probability_tails)
n=100
probability_heads_n_tails=probability(n, toss_coin(n))
probability_heads=probability_heads_n_tails[0]
print(probability_heads)
probability_tails=probability_heads_n_tails[1]
print(probability_tails)

0.3
0.7
0.35
0.65


We will now see a sample code where we will calculate conditional probability. The condition of calculating the probability is such, that you first draw a face card (which is a given situation) and after you draw this first card what is the probability that your next card will be an ace? 
Note: There are 4 Aces and 12 Face cards in a deck of 52 cards.

In [ ]:
 #Create function that returns probability percent rounded to one decimal place
def event_probability(event_outcomes, sample_space):
    probability = (event_outcomes / sample_space)
    return round(probability, 6)


# Sample Space
cards = 52

# Outcomes
aces = 4

# Divide possible outcomes by the sample set
ace_probability_percent = event_probability(aces,cards) *100

# Print probability percent rounded to one decimal place
print("probability % of finding aces, rounded to one decimal place: "+str(round(ace_probability_percent, 3)) + '%')


# Probability of drawing an ace, given you had just drawn a face card if you are the first player (the deck is NOT shuffled after the first draw)

face_cards = 12
face_card_probability = event_probability(face_cards, cards-1) # this is also the probability of the evidence

ace_probability= event_probability(aces,cards) #this is also the probability of the hypothesis

probability_face_card_n_ace=face_card_probability*ace_probability

conditional_probability= probability_face_card_n_ace / face_card_probability

print("probability % of drawing an ace, given a face card was just drawn: "+str(round(conditional_probability,5)*100)+'%')


probability % of finding aces, rounded to one decimal place: 7.692%
probability % of drawing an ace, given a face card was just drawn: 7.692%


#Question:8
From a given deck of 52 cards you first draw a king. What is the probability of finding another king from the same deck, considering the first card is already outside of the deck now? Write a code to calculate the conditional probability of getting the second card as another king.

In [ ]:
 #Create function that returns probability percent rounded to one decimal place
def event_probability(event_outcomes, sample_space):
    probability = (event_outcomes / sample_space)
    return round(probability, 6)


# Sample Space
cards = 51

# Outcomes
aces = 3

# Divide possible outcomes by the sample set
ace_probability_percent = event_probability(aces,cards) *100

# Print probability percent rounded to one decimal place
print("probability % of finding aces, rounded to one decimal place: "+str(round(ace_probability_percent, 3)) + '%')


# Probability of drawing an ace, given you had just drawn a face card if you are the first player (the deck is NOT shuffled after the first draw)

face_cards = 11
face_card_probability = event_probability(face_cards, cards-1) # this is also the probability of the evidence

ace_probability= event_probability(aces,cards) #this is also the probability of the hypothesis

probability_face_card_n_ace=face_card_probability*ace_probability

conditional_probability= probability_face_card_n_ace / face_card_probability

print("probability % of drawing an ace, given a face card was just drawn: "+str(round(conditional_probability,5)*100)+'%')


probability % of finding aces, rounded to one decimal place: 5.882%
probability % of drawing an ace, given a face card was just drawn: 5.882%


In [ ]:
#Create function that returns probability percent rounded to one decimal place
def event_probability(event_outcomes, sample_space):
 probability = (event_outcomes / sample_space)
 return round(probability, 3)
# Sample Space
cards = 52
# Outcomes
king_cards= 4
king_card_probability = event_probability(king_cards, cards) # this is also the probability of the evidence
another_king_card_probability= event_probability(king_cards-1,cards-1) #this is also the probability of the hypothesis and the second card draw
probability_king_and_another_king = king_card_probability * another_king_card_probability #the probability of the intersection between the two events
conditional_probability= probability_king_and_another_king / king_card_probability
print("probability % of drawing an ace, given a face card was just drawn: "+str(round(conditional_probability*100,4))+'%')

probability % of drawing an ace, given a face card was just drawn: 5.9%
